language: ruby
install:
- bundle install
script: bundle exec rake site:deploy
env:
  global:
    secure: gF3I79y73L27kdOVob0lMTxHkienCn86lbNvQ2erGQfd+UEuvrZqp7qKG/alosLlY9Q1vHlixORbbVSOEOfWF+S1hC0YrsQCXKF/Ll840ll1a8xNtgl+H+ywl+YzVQ+rTGyCTyqOYRPsULkC7yI4fUxSLUe6WPvkAStbp+SW4clSpFfnTfTzVF+HiCfqwpVHJ8MpF7+99CXFBYbbGyjSzUTg+YGds9dg/tx+5u6tpGUHF1eIr7nqKKI9iLDYb/NPjr7MuWb1iulj4OrEeQTHipp+chsvEk4HI346fFthfrpWvx1aBOyzi+aWYLTbLWuy8B9DiXX6gKFatDJmq2tK10TCEG55N8Rk9qNgOp7r5CQ1z/VqR8VCiQb/YlEWAdlT8kPrJYjogCQXHmGbKS2MDvs/SNE5v+S7r64v6YC/j1gj9Bog/VPC7EqjmLUJLf8ddNg+2b2gH0fvwT8DwWHwxxWuIRJ81ylDLQLrlGx6+rg33aM9Rg2rqLoTHIq4WfPe65KwHYU3fadzBhbazoSmvtFjf+2M39whrftjLtheQcxWederxJDe11OcItaQYO1eKctvxcprwzVqYoxqC/ej6/LzafFB4f5Yc4j+D5//8WRRfG6bD+V5kJiTrjHwKiGeNhNpRvwTupA7HKFj1n5rseoMR2YsinEmE4jEPgDagYI=
