language: ruby
install:
- bundle install
script: bundle exec rake site:deploy
env:
  global:
    secure: oou9sMNFZOKGL3Ii4sa3zbKa0hCJOCf3dKwdCTz5I/KUKIq8jTbVcBfKs+N4fWOAeTo0DC2WYftW9wUcsNlYwZC9XLbWJ2psxBku2GcVEVcozHyi2seJLiCIim9vecTR1ViCm/sDcAFB56K5yLVRwOW8t1npfWF5fPIG1fvMJCEu1keHK1+1Ku3zmGNKrrcv43+Fw52TO2EEYPRofaM2AZXSao3qC8AnD/rj1GhLareOQphJgr9UgCNQjwaWutEamHB1fQoyyxuVrc+lVLcN00Y45or1yb3kiKAWUp7oQY3K4HCpX0Nb/veqgvSURqmLOWRjB7XAfF8SnUjyK0uQw/zlz2tXLM0Ms0UI4ahBAm0QeupG7mU0k/sHzLJYb9qM0r3f61kMttRjydGgNhqE7LRJmXy80TsxEE6Zgo54hrCaSrwoUDtB5EPHVDHv20UEzx5B2SNmd3YwLV71k5oko/rShVMYYLBbeslAAT3LZgHSFYi7DVoxbGEMBJNufR2S4KLdx3EpARzHhPUCVqJgYGPrqpLZVfJigM6Jv3BcYNxZHZTKdFLGpRNKwnxbBo07lGXSOzSApT0X418XKnhd4JCJyFKsCO9qk/04/u8tbpp70eO4aVNbb/l4cdHGGZi35TjrLxQ0L3LsRgJYlW++bA6q4ZZVhkStP1ihCoFH3OI=
