language: ruby
install:
- bundle install
#script: bundle exec rake site:deploy
script: bundle exec jekyll build
branches:
  only:
    - gh-pages     
    - /pages-(.*)/ 

env:
  global:
    secure: "S4maj7QvWBHkFlJqcgmV6cfmGq2tgYaEI/Ivn2wC9PYlv8fF7GaF5D5MfrmYXb5ZsOI8GOjAFHEJuAhWR0cUUQS6z0pxOQbBKET2IE216pzX0C8Gkg2M6MU+vIb79xAP21m9RFucSe8y1WN/WpJvI3cn9PeBLB/XCAPjcl6BMU24aW3MehTP7E3KOeBLISygZAglpja0nCUv9nRgoXvLczhZN7yZnP7y44qKAYHcDid1zrJOPo+wWbhSWvX9o/tvZd/m21uNGV6xwaieTbwfWtuBIsnMgaZ4yAy/Chn9kzdrKfYY2PjqncP8CoJKw26dMcds/bAHT6zXuqinimgDTTpnw5LP8RfD0Q4tvXFtrNsliJ1e0p7gBh8Ck0gZkBu8DsoiJWMuZRxo0Whg+dv2jl3xLrnOcfKS2yRsjQVLyXm0gbt+iP6ENKFFTwHJ69AVw+gLI4pjdstZvub/dCxuytyngldfLgY1osGQryybzpACMAVtl0UceGft6hUVzdzZPQG12fMLgjQjEySgwdU7f+vMHGNNVOt/6KFiMlHcSfUK2ot0i5Rp4QOR1+n3bN1oblM4UGbKEPZyfjcDrNl1xAl7aNQpl0QAKb0d99Py+fmF5+HcF9yg6KW3pbcW1QjXNsbv7WSqEpq9gHMUDm8WFmV3KOG+80iYLOmT14hGFSg="


exclude: [vendor]
