safe: false
lsi: false
highlighter: 'pygments'

relative_source: ../captor/
destination: _site

github_user: zsivienna
source_repo: captor
destination_repo: zsivienna.github.io

# Settings for deploy rake task
# Username and repo of Github repo, e.g.
# https://github.com/USERNAME/REPO.git
# username defaults to ENV['GIT_NAME'] used by Travis
# repo defaults to USERNAME.github.io
# Branch defaults to "source" for USERNAME.github.io
# or "master" otherwise
username: zsivienna
repo: captor
branch: master

branches:
  only:
  - gh-pages
  - /pages-(.*)/

permalink: none

exclude:
  - README.md
  - Rakefile
  - Gemfile
  - Gemfile.lock
  - changelog.md
  - "*.Rmd"
  - vendor
  - .travis.yml

title: CAPTOR
email: dev@zsi.at
description: > 
    Air pollution is THE environmental topic that European citizens worry about most.
    It is responsible for 400,000 premature deaths in Europe each year,
    and puts considerable damage to agriculture as well as our natural environment.
baseurl: ""
url: "http://zsivienna.github.io"

# Build settings
markdown: kramdown




