safe: false
lsi: false
pygments: true

relative_source: ../captor/
destination: ../zsivienna.github.io/

github_user: ZSIVienna
source_repo: captor
destination_repo: zsivienna.github.io

permalink: none

exclude:
  - README.md
  - Rakefile
  - Gemfile
  - Gemfile.lock
  - changelog.md
  - "*.Rmd"
  - vendor
  - .travis.yml

title: CAPTOR
email: dev@zsi.at
description: > 
    Air pollution is THE environmental topic that European citizens worry about most.
    It is responsible for 400,000 premature deaths in Europe each year,
    and puts considerable damage to agriculture as well as our natural environment.
baseurl: ""
url: "http://zsivienna.github.io"

# Build settings
markdown: kramdown




